### PR TITLE
docs(README) add troubleshoot section

### LINKED ISSUE #4: don't work with my init.lua
Hi,

I don't know who is the culprit, but when I try to run `:Telescope neoclip` nothing happen, no telescope window opens.

Here is my [init.lua](https://github.com/doums/dotfiles/blob/master/.config/nvim/init.lua).

I just added
```
require'neoclip'.setup()
```
to my init.lua.

Update: It works when I use `:lua require('telescope').extensions.neoclip.default()`. Maybe there is a problem when the plugin manager is not packer (I use paq).

### PR DESCRIPTION
**Pull request by AckslD**
closes #4

### CODE REVIEW

**Comment by jandamm** [comment]
For me it doesn't work with packer either.
I only load `telescope` on `cmd = 'Telescope'` and `module = 'telescope'`.

**Comment by AckslD** [comment]
@jandamm Hmm I see, not sure why that is though. At least it's not a big issue since you can do `:Telescope neoclip neoclip` or `:Telescope neoclip default` for the same behaviour. Does that work for you?

**Comment by jandamm** [comment]
I'll try that.
For now I've fixed it by adding the neoclip extension manually in the telescope config.

**Comment by jandamm** [comment]
Works for me with `Telescope neoclip default`
Using that now 👍

**Comment by AckslD** [comment]
Great @jandamm :)

**Pull request merged**
