### PR TITLE
change requires to dependencies for auto-installation in neovim

### PR DESCRIPTION
**Pull request by sudoAlphaX**

### CODE REVIEW

**Comment by AckslD** [comment]
@sudoAlphaX sorry for a very late reply. Would you want to reopen this again?

**Comment by sudoAlphaX** [comment]
This PR was a mistake. I had wrongly assumed that the package manager used it Lazy, but i didnt notice the `use` keyword, isntead of `return` used my Lazy.
Hence, I closed this PR.
But if the keyword for dependencies in the package manager used in the example (I think it is packer, I could be wrong), Ill be happy to reopen this PR.

**Comment by AckslD** [comment]
Oh! I made the same mistake now :P Yeah indeed this plugin was written prior to `lazy.nvim` and assumed `packer`. It's not ideal that this is not specified in the README though. If you would want to update the instructions to use `lazy.nvim` I'd be happy with that!

**Comment by sudoAlphaX** [comment]
I'd be glad to do that. Will open a PR after adding a snippet for Lazy package manager, and also an example config for activate.nvim.


-------- Original Message --------

**Pull request closed without merging**
